version: "3.8"

services:
  llm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company_llm_container
    volumes:
      - .:/app
      - hf-cache:/root/.cache/huggingface
    ports:
      - "8742:8742"
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8742/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_DEFAULT_REGION=eu-central-1
      - HF_TOKEN=${HF_TOKEN}

volumes:
  hf-cache:
